import torch
# x= torch.arange(20)
# print(x)
# print(x.shape)
# print(x.numel())
# print(x.size())
# X = x.reshape(4,5)
# print(X)
# y = torch.zeros(2,3,4)
# print(y)
# z = torch.ones(2,3,4)
# print(z)
# a = torch.randn(2,3,4)
# print(a)
#
# b = torch.randn(3,4)
# print(b)
# x = torch.tensor([1.0,2,4,8])
# y = torch.tensor([2,2,2,12])
# print("x + y = ",x + y)
# print("x - y = ",x - y)
# print("x * y = ",x * y)
# print("x / y = ",x / y)
# print("x ** y = ",x ** y)
# print(torch.exp(x))
# x = torch.arange(12, dtype=torch.float32).reshape((3,4))
# y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
# print(torch.cat((x,y),dim=0))
# print(torch.cat((x,y), dim=1))
# print(x==y)
# print(x.sum())
# a = torch.arange(3).reshape((3,1))
# b = torch.arange(2).reshape((1,2))
# print("a: \n", a)
# print("b: \n", b)
# print("a+b: \n", a+b)
a = torch.tensor([3.5])
print("a: \n", a)
print("a.item(): \n", a.item())
print("float(a): \n", float(a))
print("int(a): \n", int(a))


